/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TweetCard {
        "author": string;
        "createdAt": string;
        "likes": string;
        "message": string;
        "tweetId": string;
    }
    interface TweetCreate {
    }
    interface TweetSign {
        "btnLabel": string;
        "formTitle": string;
        "img": string;
        "password": string;
        "username": string;
    }
}
export interface TweetCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTweetCardElement;
}
export interface TweetCreateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTweetCreateElement;
}
export interface TweetSignCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTweetSignElement;
}
declare global {
    interface HTMLTweetCardElement extends Components.TweetCard, HTMLStencilElement {
    }
    var HTMLTweetCardElement: {
        prototype: HTMLTweetCardElement;
        new (): HTMLTweetCardElement;
    };
    interface HTMLTweetCreateElement extends Components.TweetCreate, HTMLStencilElement {
    }
    var HTMLTweetCreateElement: {
        prototype: HTMLTweetCreateElement;
        new (): HTMLTweetCreateElement;
    };
    interface HTMLTweetSignElement extends Components.TweetSign, HTMLStencilElement {
    }
    var HTMLTweetSignElement: {
        prototype: HTMLTweetSignElement;
        new (): HTMLTweetSignElement;
    };
    interface HTMLElementTagNameMap {
        "tweet-card": HTMLTweetCardElement;
        "tweet-create": HTMLTweetCreateElement;
        "tweet-sign": HTMLTweetSignElement;
    }
}
declare namespace LocalJSX {
    interface TweetCard {
        "author"?: string;
        "createdAt"?: string;
        "likes"?: string;
        "message"?: string;
        "onTweetLiked"?: (event: TweetCardCustomEvent<string>) => void;
        "tweetId"?: string;
    }
    interface TweetCreate {
        "onTweetSubmited"?: (event: TweetCreateCustomEvent<string>) => void;
    }
    interface TweetSign {
        "btnLabel"?: string;
        "formTitle"?: string;
        "img"?: string;
        "onSignSubmited"?: (event: TweetSignCustomEvent<any>) => void;
        "password"?: string;
        "username"?: string;
    }
    interface IntrinsicElements {
        "tweet-card": TweetCard;
        "tweet-create": TweetCreate;
        "tweet-sign": TweetSign;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tweet-card": LocalJSX.TweetCard & JSXBase.HTMLAttributes<HTMLTweetCardElement>;
            "tweet-create": LocalJSX.TweetCreate & JSXBase.HTMLAttributes<HTMLTweetCreateElement>;
            "tweet-sign": LocalJSX.TweetSign & JSXBase.HTMLAttributes<HTMLTweetSignElement>;
        }
    }
}
